import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <footer style={{ position: "absolute", bottom: 0, width:"100vw" }} className='text-center mx-auto px-6 pt-10 pb-6'>Hecho por Ulises Cortes</footer>
      </body>
    </html>
  )
}
