import type { Metadata } from 'next'
import { Inter, Kanit } from 'next/font/google'
import './globals.css'
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] })
const kanit = Kanit({ weight: "400", subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Quien falta',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <div className='h-max p-10.'>
          <Link
            href="/"
            className="w-"
            rel="noopener noreferrer"
          >
            <h2 className={`absolute top-5 left-5 text-sm xl:text-xl text-center font-semibold`}>
              LOGO
            </h2>
          </Link>
          {children}
          <footer className='text-center mx-auto pt-8 pb-2 xl:pt-24 xl:pb-4'>Hecho por Ulises Cortes</footer>
        </div>
      </body>
    </html>
  )
}
